megaproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from reports import views as report_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', report_views.SiteList.as_view(), name='sites'),
    url(r'', include('reports.urls')),
]

reports/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import reports.views as report_views

urlpatterns = [
    url(r'^sites/$', report_views.SiteList.as_view(), name='sites'),
    url(r'^sites/(?P<pk>\d+)/$', report_views.SiteDetail.as_view(), name='site_detail'),
    url(r'^summary/$', report_views.Summary.as_view(), name='summary'),
    url(r'^summary-average/$', report_views.Average, name='average'),
]

reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, connection

class Site(models.Model):
    name = models.CharField(max_length=100, blank=False)

    def __str__(self):
        return "%s" % self.name

class Report(models.Model):
    name = models.ForeignKey(Site, on_delete=models.CASCADE)
    date = models.DateField(blank=False, null=False)
    a_value = models.PositiveIntegerField(default=0)
    b_value = models.PositiveIntegerField(default=0)


##
# Helper functions
##

# Source:
# https://docs.djangoproject.com/en/1.11/topics/db/sql/#executing-custom-sql-directly
def dict_fetchall(cursor):
    """
    Returns all rows from a cursor as a dict,
    adding their respective field name.
    """
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def get_sites_avg():
    """
    Query the database for the name of the sites, and
    the average of their respective a_value and b_value.
    """
    raw_sql = 'SELECT name, AVG(a_value) as a_value, AVG(b_value) as b_value \
                FROM reports_report as r, reports_site as s \
                WHERE r.name_id = s.id GROUP BY s.id;'

    with connection.cursor() as c:
        c.execute(raw_sql)
        res = dict_fetchall(c)
    return res

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import DetailView, ListView

from models import Site, Report, get_sites_avg

#
# Class Based Views
#
class SiteList(ListView):
    model = Site

class SiteDetail(DetailView):
    model = Site

class Summary(ListView):
    model = Site
    template_name = 'reports/summary.html'

#
# Function Based Views
#
def Average(request):
    if request.method == 'GET':
        sites = get_sites_avg()

    return render(request, 'reports/average.html', {'sites':sites})

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{% block title %} App Name {% endblock %}</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">


</head>
<body>

<nav class="navbar navbar-default">
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        {% block navbar-nav %}
        <li class="active"><a href="/">Sites</a></li>
        <li><a href="{% url 'summary' %}">Summary</a></li>
        <li><a href="https://github.com/veduardo">Code</a></li>
        {% endblock %}
      </ul>
    </div>
</nav>

<div class="container">
  <div>
  {% block content %}

  {% endblock %}
  </div>
</div>

</body>
</html>

templates/reports/average.html
{% extends 'reports/summary.html' %}

{% load report_operations %}

{% block buttons %}
<a class="btn btn-primary" href="{% url 'summary' %}">Sum</a>
<a class="btn btn-primary active" href="{% url 'average' %}">Average</a>
{% endblock %}


{% block tbody %}
    <tbody>
    {% for site in sites %}
        <tr>
            <td>{{ site.name }}</td>
            <td>{{ site.a_value|floatformat:2 }}</td>
            <td>{{ site.b_value|floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

templates/reports/site_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Site Details - {{ site.name }}</h1>
<table class="table">
    <thead>
        <tr>
            <td><strong>Date</strong></td>
            <td><strong>A Value</strong></td>
            <td><strong>B Value</strong></td>
        </tr>
    </thead>

    <tbody>
    {% for record in site.report_set.all %}
        <tr>
            <td>{{ record.date }}</td>
            <td>{{ record.a_value|floatformat:2 }}</td>
            <td>{{ record.b_value|floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/reports/site_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Sites</h1>
<ul class="list-group">
    {% for post in object_list %}
    <li class="list-group-item"><a href="{% url 'site_detail' post.id %}">{{ post.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/reports/summary.html
{% extends 'base.html' %}

{% load report_operations %}

{% block navbar-nav %}
<li><a href="/">Sites</a></li>
<li class="active"><a href="{% url 'summary' %}">Summary</a></li>
<li><a href="https://github.com/veduardo">Code</a></li>
{% endblock %}

{% block content %}

<h1>Summary</h1>

{% block buttons %}
<a class="btn btn-primary active" href="{% url 'summary' %}">Sum</a>
<a class="btn btn-primary" href="{% url 'average' %}">Average</a>
{% endblock %}

<table class="table">
    <thead>
        <tr>
            <td><strong>Site</strong></td>
            <td><strong>A Value</strong></td>
            <td><strong>B Value</strong></td>
        </tr>
    </thead>

    {% block tbody %}
    <tbody>
    {% for site in object_list %}
        <tr>
            <td>{{ site.name }}</td>
            <td>{{ site|sum:'a'|floatformat:2 }}</td>
            <td>{{ site|sum|floatformat:2 }}</td>
        </tr>
    {% endfor %}
    </tbody>
    {% endblock%}

</table>

{% endblock %}